port: "8880"

#db:
#  username: "wallet_db_x8ck_user"
#  host: "dpg-d03ptm3e5dus73aifql0-a.oregon-postgres.render.com"
#  port: "5432"
#  dbname: "wallet_db_x8ck"
#  sslmode: "require"
db:
  username: "postgres"
  host: "localhost"
  port: "5437"
  dbname: "postgres"
  sslmode: "disable"


